### ISSUE TITLE
Effect of trait1 on trait2

### ISSUE THREAD

**Issue by gnarw** [lukejoconnor/LCV#7]
I have a question regarding the gcp zscore.
If for example the gcp between trait1 and trait2 is 0.65, I´m interested in estimating the effect trait1 has on trait2.
I´m I right in assuming that multiplying the gcp zscore with the gcp standard error gives me the causal effect (beta value) trait1 has on trait2 ?

**Comment by lukejoconnor** [comment]
No, the gcp is totally different from the magnitude of the causal effect.

The LCV model assumes that, if there is a causal effect, its size is equal to the genetic covariance (in units of trait s.e. per trait s.e.). In practice, there can be a causal effect that is not equal to the genetic covariance (due to additional pleiotropy), and this will usually look like a gcp that is not zero but also not equal to +-1. Because of this I don't recommend reporting a causal effect size, except with lots of caveats.
